<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsTableSeeder extends Seeder
{
    public function run()
    {
        $items = [
            [
                'user_id' => 1,
                'name' => '腕時計',
                'brand_name' => 'SEIKO',
                'price' => 15000,
                'description' => 'スタイリッシュなデザインのメンズ腕時計',
                'condition' => '良好',
                'color' => 'ブラック',
                'is_new' => true,
                'shipping_comment' => '購入後、即発送いたします。',
                'image_url' => 'items/腕時計.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'name' => 'HDD',
                'brand_name' => 'Western Digital',
                'price' => 5000,
                'description' => '高速で信頼性の高いハードディスク',
                'condition' => '目立った傷や汚れなし',
                'color' => 'シルバー',
                'is_new' => false,
                'shipping_comment' => '迅速に発送します。',
                'image_url' => 'items/HDD.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'name' => '玉ねぎ3束',
                'brand_name' => '北海道産',
                'price' => 300,
                'description' => '新鮮な玉ねぎ3束のセット',
                'condition' => 'やや傷や汚れあり',
                'color' => 'ホワイト',
                'is_new' => true,
                'shipping_comment' => '当日発送いたします。',
                'image_url' => 'items/玉ねぎ3束.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'name' => '革靴',
                'brand_name' => 'REGAL',
                'price' => 4000,
                'description' => 'クラシックなデザインの革靴',
                'condition' => '状態が悪い',
                'color' => 'ブラック',
                'is_new' => false,
                'shipping_comment' => '購入後、即発送いたします。',
                'image_url' => 'items/革靴.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'name' => 'ノートPC',
                'brand_name' => 'DELL',
                'price' => 45000,
                'description' => '高性能なノートパソコン',
                'condition' => '良好',
                'color' => 'グレー',
                'is_new' => true,
                'shipping_comment' => '24時間以内に発送します。',
                'image_url' => 'items/ノートPC.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'name' => 'マイク',
                'brand_name' => 'SHURE',
                'price' => 8000,
                'description' => '高音質のレコーディング用マイク',
                'condition' => '目立った傷や汚れなし',
                'color' => 'ブラック',
                'is_new' => true,
                'shipping_comment' => '当日中に発送可能です。',
                'image_url' => 'items/マイク.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'name' => 'ショルダーバッグ',
                'brand_name' => 'PORTER',
                'price' => 3500,
                'description' => 'おしゃれなショルダーバッグ',
                'condition' => 'やや傷や汚れあり',
                'color' => 'ネイビー',
                'is_new' => false,
                'shipping_comment' => '翌日発送予定です。',
                'image_url' => 'items/ショルダーバッグ.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'name' => 'タンブラー',
                'brand_name' => 'THERMOS',
                'price' => 500,
                'description' => '使いやすいタンブラー',
                'condition' => '状態が悪い',
                'color' => 'グリーン',
                'is_new' => false,
                'shipping_comment' => '準備ができ次第発送します。',
                'image_url' => 'items/タンブラー.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'name' => 'コーヒーミル',
                'brand_name' => 'HARIO',
                'price' => 4000,
                'description' => '手動のコーヒーミル',
                'condition' => '良好',
                'color' => 'ブラック',
                'is_new' => true,
                'shipping_comment' => 'スピード発送いたします。',
                'image_url' => 'items/コーヒーミル.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'name' => 'メイクセット',
                'brand_name' => 'CANMAKE',
                'price' => 2500,
                'description' => '便利なメイクアップセット',
                'condition' => '目立った傷や汚れなし',
                'color' => 'ピンク',
                'is_new' => true,
                'shipping_comment' => 'ご購入後すぐ発送いたします。',
                'image_url' => 'items/メイクセット.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('items')->insert($items);
    }
}
